### ISSUE TITLE
Some Covers not being updated on Kindle

### ISSUE THREAD

**Issue by Synthesthesia** [weto91/kindle-cover-fixer#6] opened 2023-11-22 19:31 UTC
I click the transfer to device option and it says it's done, but only some of the covers are showing up on the Kindle.

The output folder is full of the covers.

All appear true in the table.

Kindle Scribe.

Kindle Version 5.16.5 (4142890042).

Windows 11.

Thanks again.

Is it possible that it's just taking a long time on the kindle to update? It was around 200 covers.

**Comment by Synthesthesia** [comment] 2023-11-22 19:42
I'm not convinced it's an issue with your app to be honest, I've just tried adding a single book manually in airplane mode on the kindle with a custom cover, and it's not showing up either.

**Comment by Synthesthesia** [comment] 2023-11-22 20:52
I found a post talking about this issue, apparently:

"It is due to the 5.16.3 update: Scribe no longer mounts as USB mass storage, and instead uses MTP (Media Transfer Protocol) for file transfers.

Calibre has an MPT client, but will need an update to copy thumbnails over MTP for the Scribe."

Does your app use MPT?

**Comment by weto91** [comment] 2023-11-22 21:44
> I click the transfer to device option and it says it's done, but only some of the covers are showing up on the Kindle.
> 
> The output folder is full of the covers.
> 
> All appear true in the table.
> 
> Kindle Scribe.
> 
> Kindle Version 5.16.5 (4142890042).
> 
> Windows 11.
> 
> Thanks again.
> 
> Is it possible that it's just taking a long time on the kindle to update? It was around 200 covers.
Hello,

200 covers are not many, it should be a matter of seconds before they appear.
Please check on your device that the /system/thumbnails folder has the same number of Covers as the number of books detected by the application.

If the number of thumbnails and books is the same. Check those books that do not have a cover to see if Caliber has one.

In 10 minutes I will release a new version that will create logs to have greater traceability of problems that may arise, it will be version 2.1. When it is uploaded, try launching the application and repeating the process, that way you will get a log in %APPDATA%/Kindle Cover Fixer that you can send me to review exactly what may be failing.

**Comment by weto91** [comment] 2023-11-22 21:46
> I found a post talking about this issue, apparently:
> 
> "It is due to the 5.16.3 update: Scribe no longer mounts as USB mass storage, and instead uses MTP (Media Transfer Protocol) for file transfers.
> 
> Calibre has an MPT client, but will need an update to copy thumbnails over MTP for the Scribe."
> 
> Does your app use MPT?
> 
> Edit: I noticed you posted in there so I'm guessing you're aware of the MPT switch over?

Yes, the application manage the MTP for the Kindle Scribe. Is for this reason that the app can be detects if the connected device is a Kindle Scribe or Kindle (Other) (Depending on the type of connection you make with the PC (MTP or mass storage))

Look at my last comment :)

**Comment by weto91** [comment] 2023-11-22 22:02
Version 2.1 launched.

If you can, repeat the entire process and close the application, then in %APPDATA%/Kindle Cover Fixer you will find a .log file. You can send it to me here to review it to see if we see any possible errors.

To upload the file, when writing a comment, below the text box there is a button that allows you to attach files, images or whatever you need.

**Comment by Synthesthesia** [comment] 2023-11-22 22:16
Version 2.1 won't open when I click it?

**Comment by weto91** [comment] 2023-11-22 23:07
> Version 2.1 won't open when I click it?

😮  im trying in 3 different computers and is opening without any problem.. 
Have you extracted all the files from the zip?
Are you double clicking on the .exe file?

Regards.

**Comment by Synthesthesia** [comment] 2023-11-22 23:24
Yeah, the old one works fine, but that new one does nothing.

**Comment by weto91** [comment] 2023-11-22 23:27
OK, i seem is my mistake, let me check for a few minutes. I will tell you when correct the problem 😮‍💨

**Comment by Synthesthesia** [comment] 2023-11-22 23:27
Thanks again for all the help, I really appreciate it!

**Comment by weto91** [comment] 2023-11-22 23:39
> Thanks again for all the help, I really appreciate it!

No problem! I like that people use my application, and of course, that they can use it in the best possible way!

Please, download V 2.1 again, I updated the ZIP... It was an application problem that I just solved 😄

**Comment by Synthesthesia** [comment] 2023-11-22 23:43
[Kindle_Cover_Fixer.log](https://github.com/weto91/kindle-cover-fixer/files/13445026/Kindle_Cover_Fixer.log)
There's the log :)

**Comment by weto91** [comment] 2023-11-22 23:44
> [Kindle_Cover_Fixer.log](https://github.com/weto91/kindle-cover-fixer/files/13445026/Kindle_Cover_Fixer.log) There's the log 😄

OK, thanks! let me check 😄

**Comment by Synthesthesia** [comment] 2023-11-22 23:45
They work when I email them from calibre too :S

**Comment by weto91** [comment] 2023-11-22 23:46
Did you tell me that your kindle was the kindle scribe? Is it the only Kindle connected to the PC?

**Comment by Synthesthesia** [comment] 2023-11-22 23:47
Yes it's a scribe, and I MAY have had my oasis plugged in when I did it then, I don't think it was though. I'll run it again and add another log.

**Comment by weto91** [comment] 2023-11-22 23:47
Yes please, thats a point that the application does not manage.. (In next versions..). Its can only manage 1 connected kindle.

**Comment by Synthesthesia** [comment] 2023-11-22 23:48
[Kindle_Cover_Fixer.log](https://github.com/weto91/kindle-cover-fixer/files/13445050/Kindle_Cover_Fixer.log)
There you go :)

**Comment by weto91** [comment] 2023-11-22 23:51
> [Kindle_Cover_Fixer.log](https://github.com/weto91/kindle-cover-fixer/files/13445050/Kindle_Cover_Fixer.log) There you go :)

Checking it 😄

**Comment by weto91** [comment] 2023-11-22 23:53
Now only the Scribe is connected?
In the log it appears that a Kindle is connected that does not connect via MTP (Paperwhite, oasis... Anyone except a Scribe). Can you send me the Scribe firmware version?

**Comment by Synthesthesia** [comment] 2023-11-22 23:56
Yeah only the scribe.

Firmware is Kindle Version 5.16.5 (4142890042).

**Comment by weto91** [comment] 2023-11-22 23:57
And how many covers are not transferred?

I see you have 203 books, apparently it transfers 203 covers.

I only see that the kindle is connected, it is not via MTP. You may have to update the application to add more data to the log...

**Comment by Synthesthesia** [comment] 2023-11-23 00:00
I'd have to count, but there's a lot. There's 37 Gantz volumes and I think it only has a cover for 1 or 2. I've generated another log after deleting it and redoing it with only the scribe connected if that makes any difference.
[Kindle_Cover_Fixer.log](https://github.com/weto91/kindle-cover-fixer/files/13445096/Kindle_Cover_Fixer.log)

**Comment by weto91** [comment] 2023-11-23 00:00
> Yeah only the scribe.
> 
> Firmware is Kindle Version 5.16.5 (4142890042).

- OK, its the last version. So, confirm me how many covers are not transferred.. 
- When you list the books, all UUIDs listed have the same format?



But i think for tomorrow morning (Here it is 00:00 AM and i need go to sleep... 😄 ) i will update the application to log more details...

**Comment by weto91** [comment] 2023-11-23 00:00
> I'd have to count, but there's a lot. There's 37 Gantz volumes and I think it only has a cover for 1 or 2. I've generated another log after deleting it and redoing it with only the scribe connected if that makes any difference. [Kindle_Cover_Fixer.log](https://github.com/weto91/kindle-cover-fixer/files/13445096/Kindle_Cover_Fixer.log)

OK, i will check

**Comment by weto91** [comment] 2023-11-23 00:07
OK, in the last log i can see the scribe . 
But it appears as if all the covers were transferred correctly...

Tomorrow morning I will update the application so that it shows me more complete logs. However, try doing the following:

- In your file explorer, open your kindle scribe/internal storage.
- In the address bar that appears above, add /system/thumbnails to the address
- Delete ALL the images in that folder
- Launch the application again and try to see if the covers are displayed correctly.


Also, if you can check: Tell me in what format you transfer the books to Kindle.

**Comment by Synthesthesia** [comment] 2023-11-23 00:15
129 missing if I counted correctly.

**Comment by weto91** [comment] 2023-11-23 00:21
After deleting the images from the Kindle and regenerating them with the app, tell me how many images are in the same Kindle directory. Let's see if it is a problem in the transfer or there is something else on the kindle that we are not taking into account...

**Comment by Synthesthesia** [comment] 2023-11-23 00:35
203 images in the kindle folder after it is done transferring.

**Comment by weto91** [comment] 2023-11-23 00:40
ok, tomorrow I will update the application to obtain more complete logs and review more things... now I have run out of ideas, since it is transferring all the images... and also I think you told me that on your other kindle it was working well, right?

  Tomorrow we can continue checking. sorry for the disturbances...

**Comment by Synthesthesia** [comment] 2023-11-23 00:43
On my Kindle Oasis it works just transferring from Calibre.

**Comment by Synthesthesia** [comment] 2023-11-23 06:08
I've discovered that it's if I use mobi files I don't get any covers, if I use epubs it works perfectly. Any idea why that is? Either way, I'm happy I can get them showing now so thanks for mentioning the formats thing!

**Comment by weto91** [comment] 2023-11-23 07:55
> I've discovered that it's if I use mobi files I don't get any covers, if I use epubs it works perfectly. Any idea why that is? Either way, I'm happy I can get them showing now so thanks for mentioning the formats thing!

Uhm, is very strange.. It should work with mobi files without problem.

this afternoon, if it is not a problem for you, I will let you know when I update the application so that it has more logs, this way we can try to see what happens... I think the problem can come from several places, among them the caliber json files in the root of the kindle they are wrong

**Comment by weto91** [comment] 2023-11-23 16:08
OK, I have done quite a few tests and I think I have managed to reproduce your problem:
To reproduce your problem (This does not have to be what has happened to you) In Caliber I have created a new library and copied all the books from one library to another. What is the surprise? that despite being the same books, the UUID changes. So choosing that library, no UUID with the correct name is generated.

In your case, this could have happened for many reasons. For example, at some point between transferring the book to Kindle and executing the program:
- You have modified any metadata of the book.
- You have modified the book itself
- You have converted the book to another format
- You have deleted a book from the library, and added it back later.

There may be more ways than those listed above to reproduce the problem.

The only solution is to synchronize caliber with the data uploaded to Kindle, to do this you simply have to RE-UPLOAD the book/library from Caliber to Kindle and then run my application.

**Comment by weto91** [comment] 2023-11-23 16:15
If you can try my recommendation from the last comment to see if it actually solves the problem. I would appreciate it, so we can close the issue (However, I am going to implement a system to check if this type of thing is happening).

Thank you!

**Comment by Synthesthesia** [comment] 2023-11-23 21:33
> OK, I have done quite a few tests and I think I have managed to reproduce your problem: To reproduce your problem (This does not have to be what has happened to you) In Caliber I have created a new library and copied all the books from one library to another. What is the surprise? that despite being the same books, the UUID changes. So choosing the new library, the UUID of the books was a different one.
> 
> In your case, this could have happened for many reasons. For example, at some point between transferring the book to Kindle and executing the program:
> 
> * You have modified any metadata of the book.
> * You have modified the book itself
> * You have converted the book to another format
> * You have deleted a book from the library, and added it back later.
>   (That's why as soon as you converted to epub and sent the book back to the Kindle, all the covers appeared correctly. )
> 
> There may be more ways than those listed above to reproduce the problem.
> 
> The only solution is to synchronize caliber with the data uploaded to Kindle, to do this you simply have to RE-UPLOAD the book/library from Caliber to Kindle and then run my application.
> 
> So my recommendation: Convert (again) your books to MOBI, AZW3 or whatever format you prefer. Send them back to Kindle, run the app again and you won't have any problems with your covers.

I did transfer some from my old Kindle, some of them were completely new however and also didn't work.

**Comment by weto91** [comment] 2023-11-23 23:31
Okay!, then I'll close the issue. Any other problems, don't hesitate to let me know!

**Closed by weto91** 2023-11-23 23:31 UTC
